import { Outfit } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

const outfitFont = Outfit({
  subsets: ["latin"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${outfitFont.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header>
          <Navbar></Navbar>
        </header>

        <main className="flex-grow ">
          {children}
        </main>

        <footer>
          <Footer></Footer>
        </footer>


        <ToastContainer />
      </body>
    </html>
  );
}
